const nodemailer = require('nodemailer');

class EmailService {
  constructor() {
    this.transporter = nodemailer.createTransporter({
      host: process.env.EMAIL_HOST,
      port: process.env.EMAIL_PORT,
      secure: false,
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      }
    });
  }

  async sendScanReport(user, scanData) {
    const { url, results, securityScore, riskLevel, vulnerabilities } = scanData;
    
    const riskColor = {
      'Low': '#28a745',
      'Medium': '#ffc107',
      'High': '#fd7e14',
      'Critical': '#dc3545'
    };

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Security Scan Report</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f8f9fa; }
          .container { max-width: 600px; margin: 0 auto; background: white; }
          .header { background: linear-gradient(135deg, #007BFF, #00d4ff); color: white; padding: 30px; text-align: center; }
          .content { padding: 30px; }
          .score-badge { display: inline-block; padding: 10px 20px; border-radius: 25px; color: white; font-weight: bold; margin: 10px 0; }
          .vulnerability { background: #f8f9fa; border-left: 4px solid #dc3545; padding: 15px; margin: 10px 0; }
          .footer { background: #f8f9fa; padding: 20px; text-align: center; color: #6c757d; }
          .btn { display: inline-block; padding: 12px 24px; background: #007BFF; color: white; text-decoration: none; border-radius: 6px; margin: 10px 0; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🛡️ Security Scan Report</h1>
            <p>Network Security Analyzer</p>
          </div>
          
          <div class="content">
            <h2>Hello ${user.name}!</h2>
            <p>Your security scan for <strong>${url}</strong> has been completed.</p>
            
            <div style="text-align: center; margin: 20px 0;">
              <div class="score-badge" style="background-color: ${riskColor[riskLevel]};">
                Security Score: ${securityScore}/100
              </div>
              <div class="score-badge" style="background-color: ${riskColor[riskLevel]};">
                Risk Level: ${riskLevel}
              </div>
            </div>

            <h3>📊 Scan Summary</h3>
            <ul>
              <li><strong>SSL Protocol:</strong> ${results.ssl?.protocol || 'N/A'}</li>
              <li><strong>Open Ports:</strong> ${results.ports?.length || 0} ports detected</li>
              <li><strong>Security Headers:</strong> ${Object.keys(results.headers || {}).length} headers analyzed</li>
              <li><strong>Vulnerabilities Found:</strong> ${vulnerabilities?.length || 0}</li>
            </ul>

            ${vulnerabilities && vulnerabilities.length > 0 ? `
              <h3>⚠️ Vulnerabilities Detected</h3>
              ${vulnerabilities.map(vuln => `<div class="vulnerability">${vuln}</div>`).join('')}
            ` : '<div style="background: #d4edda; border-left: 4px solid #28a745; padding: 15px; margin: 10px 0;">✅ No critical vulnerabilities detected!</div>'}

            <div style="text-align: center; margin: 30px 0;">
              <a href="${process.env.FRONTEND_URL || 'http://localhost:8080'}" class="btn">View Full Report</a>
            </div>
          </div>
          
          <div class="footer">
            <p>This report was generated by Network Security Analyzer</p>
            <p>© ${new Date().getFullYear()} ACE Engineering College</p>
          </div>
        </div>
      </body>
      </html>
    `;

    const mailOptions = {
      from: process.env.EMAIL_FROM,
      to: user.email,
      subject: `🛡️ Security Scan Report for ${url}`,
      html: htmlContent
    };

    try {
      await this.transporter.sendMail(mailOptions);
      console.log(`Email sent successfully to ${user.email}`);
      return { success: true };
    } catch (error) {
      console.error('Email sending failed:', error);
      return { success: false, error: error.message };
    }
  }

  async sendWelcomeEmail(user) {
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Welcome to Network Security Analyzer</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f8f9fa; }
          .container { max-width: 600px; margin: 0 auto; background: white; }
          .header { background: linear-gradient(135deg, #007BFF, #00d4ff); color: white; padding: 30px; text-align: center; }
          .content { padding: 30px; }
          .btn { display: inline-block; padding: 12px 24px; background: #007BFF; color: white; text-decoration: none; border-radius: 6px; margin: 10px 0; }
          .footer { background: #f8f9fa; padding: 20px; text-align: center; color: #6c757d; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🌐 Welcome to Network Security Analyzer!</h1>
          </div>
          
          <div class="content">
            <h2>Hello ${user.name}!</h2>
            <p>Welcome to the Network Security Analyzer platform. Your account has been successfully created with <strong>${user.role}</strong> privileges.</p>
            
            <h3>🚀 What you can do:</h3>
            <ul>
              <li>🔍 Perform comprehensive security scans</li>
              <li>📊 View detailed vulnerability reports</li>
              <li>📈 Track your scan history</li>
              <li>📧 Receive email notifications for scan results</li>
              ${user.role === 'Developer' ? '<li>⚙️ Access advanced developer features</li>' : ''}
            </ul>

            <div style="text-align: center; margin: 30px 0;">
              <a href="${process.env.FRONTEND_URL || 'http://localhost:8080'}" class="btn">Start Your First Scan</a>
            </div>
          </div>
          
          <div class="footer">
            <p>Network Security Analyzer - ACE Engineering College</p>
            <p>© ${new Date().getFullYear()} All rights reserved</p>
          </div>
        </div>
      </body>
      </html>
    `;

    const mailOptions = {
      from: process.env.EMAIL_FROM,
      to: user.email,
      subject: '🌐 Welcome to Network Security Analyzer!',
      html: htmlContent
    };

    try {
      await this.transporter.sendMail(mailOptions);
      return { success: true };
    } catch (error) {
      console.error('Welcome email sending failed:', error);
      return { success: false, error: error.message };
    }
  }
}

module.exports = new EmailService();